In [2]:
import tensorflow as tf
import numpy as np
tf.compat.v1.set_random_seed(777)  # for reproducibility

In [5]:
tf.compat.v1.disable_eager_execution()

In [6]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.compat.v1.placeholder("float", [None, 4])
Y = tf.compat.v1.placeholder("float", [None, 3])
nb_classes = 3

In [13]:
W = tf.compat.v1.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.compat.v1.Variable(tf.random.normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis), axis=1))

optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 15.9351845
200 0.6264014
400 0.50995004
600 0.41032776
800 0.3160345
1000 0.25137627
1200 0.226244
1400 0.2056312
1600 0.1883741
1800 0.17371076
2000 0.1611003
--------------
[[6.4921486e-03 9.9350303e-01 4.7717431e-06]] [1]
--------------
[[0.8524848  0.14404917 0.003466  ]] [0]
--------------
[[1.1745356e-08 3.0165736e-04 9.9969840e-01]] [2]
--------------
[[6.4921547e-03 9.9350303e-01 4.7717340e-06]
 [8.5248500e-01 1.4404909e-01 3.4660024e-03]
 [1.1745356e-08 3.0165765e-04 9.9969840e-01]] [1 0 2]
